theme: jekyll-theme-Cayman
title: Avnish webpage
description: Welcome to my personal site
url: "https://avnishd2105.github.io"
baseurl: ""
author: "Avnish Deshmukh"
show_downloads: false
color_scheme: dark

# Adding profile picture
profile_image: /profile_picture.jpej # Ensure the path matches your image location

social_links:
  - name: GitHub
    url: https://github.com/avnishd2105
  - name: LinkedIn
    url: https://www.linkedin.com/in/avnish-deshmukh
  - name: Instagram
    url: https://www.instagram.com/av.nish2105/
