theme: jekyll-theme-Cayman
title: Avnish Deshmukh
description: "Explore Avnish Deshmukh's journey in robotics, coding, and electronics. Discover innovative projects, insights, and experiences shared through tech-focused articles and showcases."
url: "https://avnishd2105.github.io"
baseurl: ""
author: "Avnish Deshmukh"
show_downloads: false
color_scheme: light

# Adding profile picture
profile_image: /profile_picture.jpeg # Ensure the path matches your image location

plugins:
  - jekyll-seo-tag

social_links:
  - name: GitHub
    url: https://github.com/avnishd2105
  - name: LinkedIn
    url: https://www.linkedin.com/in/avnish-deshmukh
  - name: Instagram
    url: https://www.instagram.com/av.nish2105/
